displayName=Shortest Path
author=Runemoro,Skretzo,FIrgolitsch,wvanderp,mpickering
description=Draws the shortest path to a chosen destination on the map (right click a spot on the world map to use)
tags=pathfinder,map,waypoint,navigation,tileman,tilebound,closest,quickest
plugins=shortestpath.ShortestPathPlugin
build=standard
version=1.20.7
